f=open("code/src/App.tsx","r",encoding="utf-8")
c=f.read()
f.close()
c=c.replace('import { openUrl } from "@tauri-apps/plugin-shell";','import { open } from "@tauri-apps/plugin-shell";')
c=c.replace('await openUrl(authUrl);','await open(authUrl);')
f=open("code/src/App.tsx","w",encoding="utf-8")
f.write(c)
f.close()
print("OK")